source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target ‘LiMi' do
    pod 'Kingfisher'
    pod 'SnapKit', '~> 4.0'
	pod 'MJRefresh', '~> 3.1.12'
	pod 'SVProgressHUD'
	pod 'SwiftyJSON'
	pod 'IQKeyboardManagerSwift'
    pod 'Moya/RxSwift'
	pod 'DZNEmptyDataSet'
	pod 'TZImagePickerController'
	pod 'ObjectMapper'
	pod 'SwiftyUserDefaults'
    pod 'Masonry'
    pod 'YYText'
    pod 'YYImage'
    pod 'MJRefresh'
    pod 'Qiniu', '~> 7.2.2'
    pod 'QiniuUpload'
    pod 'XLPhotoBrowser+CoderXL'
    pod 'DZNEmptyDataSet'
#    pod 'XLPagerTabStrip', '~> 8.0'
#    pod 'AGEmojiKeyboard'
#    pod 'PageMenu'
#    pod 'SPPageMenu'
#   pod 'Moya/RxSwift'
end
